### ISSUE TITLE
Located easily fixable issue with the predict() function

### ISSUE THREAD

**Issue by RussellGrayxd** [cran/sdm#3]
Accidentally figured out a potential quick-fix for the predict function error:
**Error in .GDALnodatavalue(dataformat) : cannot find matching nodata value**

I had ran **options(scipen = -100, digits = 2)** to put the output into scientific notation for reporting purposes. Afterward, when running the predict function I got the error. When I changed it back to standard notation with **options(scipen = 999, digits = 2)** the function ran with no issues. 

Not sure this needs any attendance within the function itself, but good to know in case anyone else runs into it. 

Cheers!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
